# when all windows are closed, open launcher
# if in lock workspace, open password prompt

# when a window opens in a workspace
# if its not the first one, make it floating

exec_always '{ swaymsg -m -t subscribe "[\"window\"]" || swaymsg reload } | jq'
# change: focus
# if window is tiling, kill floating windows in workspace, remove opacity
# if window is floating: swaymsg "[workspace=__focused__ tiling] opacity "

# to close a window
# Super+space
# Alt+Escape

# super/alt+<num>:
# if Application.screens[num] is not empty, just focus the screen, otherwise move the current window along,
# and store its appid and title, in ~/.config/ushell/screens
# super/alt+0 removes the window from the screen and the config file

# if appid and title matches a line in $HOME/.config/ushell/screens, create the surface in that screen

# hide cursor after 8 seconds, and when typing begins

# lock
# switch to workspace lock, go to lock mode, and if workspace is empty, run: uni lock
# super, alt+tab or click on statusbar: toggle password prompt
# password prompt closes (showing  in lock mode) when Escape is pressed,
# 	or when empty password is entered, or simply when password prompt is unfocused
# start in locked mode
# lock after 10m idle, if lock inhibit is not active
# before lock, show a 10s countdown screen
#
# check for the password of user "nu":
# su nu -c true
#
# plugged in: lock after 10 min idle, turn off display after 15 min idle
# battery: decrease brightness after 5 min idle, lock after 10 min idle, turn off display after 11 min idle
# low battery: decrease brightness after 2 min idle, lock and turn off display after 4 min idle,
# 	suspend after 5 min idle
# https://wiki.archlinux.org/title/Backlight
# https://github.com/FedeDP/Clight/wiki/Modules#wayland-support
# https://quickshell.org/docs/v0.1.0/types/Quickshell.Widgets/WrapperItem/
# https://doc.qt.io/qt-6/qml-qtquick-effects-multieffect.html
#
# https://wiki.archlinux.org/title/Power_management
# battery
# power profiles (latency config) https://docs.kernel.org/power/pm_qos_interface.html
# 	https://github.com/linrunner/TLP
# https://github.com/Hummer12007/brightnessctl
#
# 30s idle after lock, poweroff screen
# in modern systems, other hardwares (cpu, network ...) are automatically put into low consumption (high latency) mode,
# 	unless an application specifically request for low latency using Linux PM QoS
# 	https://docs.kernel.org/power/pm_qos_interface.html

# https://github.com/jjsullivan5196/wvkbd
# https://git.sr.ht/~earboxer/swipeGuess

# voice control
# like keyboard input, if the word is not a registered command, pass it to focused window
# https://www.speedofsound.io/
# https://github.com/kavehtehrani/speech2text-extension/
# https://github.com/k2-fsa/sherpa-onnx
# https://github.com/Saim20/willow
# https://github.com/Manish7093/IBus-Speech-To-Text
# https://github.com/canonical/myna
# https://github.com/mkiol/dsnote
# https://easyspeak.dev/latest/
# https://github.com/g0dd4rd/anthony/

# uni
