output * bg #222222 solid_color

input type:touchpad {
	tap enabled
	scroll_method two_finger
	natural_scroll enabled
}
seat * hide_cursor 100

exec swayidle -w timeout 600 'dbus-send swaylayer-lock'

# when the state of a window changes:
# if the focused window is tiling, kill all floating windows of current workspace
# 	then if it's not the first window of workspace, make it floating
# if the focused window is floating, open a dimmer
# if workspace is empty, open the launcher
exec '{ swaymsg -m -t subscribe "[\"window\"]" || swaynag -m "floater failed"; } | while read _; do \
	if swaymsg "[con_id=__focused__ tiling] focus"; then \
		swaymsg "[workspace=__focused__ floating] kill"; \
		swaymsg focus prev && swaymsg "focus next; floating enable"; \
	elif swaymsg "[con_id=__focused__ floating] focus"; then \
		dbus-send; \
	else \
		dbus-dbus; \
	fi; \
done'

no_focus [app_id=swaydim]
for_window [app_id=swaydim] opacity 0.5, floating enable, resize grow 100ppt

# if appid and title matches a line in $HOME/.config/ushell/screens,
# create the surface in the workspace named after that screen's number

# hide cursor after 8 seconds
seat * hide_cursor 8000

bindsym Mod4+BackSpace kill
bindsym Mod1+Escape kill

bindsym --release Super_L dbus-send launcher
bindsym --release Super_R dbus-send launcher
bindsym Mod1+Tab dbus-sebd launcher
bindsym Mod4+space dbus-send launcher-superprompt

workspace_auto_back_and_forth yes

exec python3 $$USHELL_DIR/swaylay.py

