
output * bg #222222 solid_color

input type:touchpad {
	tap enabled
	scroll_method two_finger
	natural_scroll enabled
}
seat * hide_cursor 100

exec swayidle -w timeout 600 'dbus-send'

# when the state of a window changes:
# if the focused window is tiling, kill all floating windows of current workspace
# 	then if it's not the first window of workspace, make it floating
# if the focused window is floating, open a dimmer
# if workspace is empty, open the launcher (or if in lock workspace, open password prompt)
exec_always '{ swaymsg -m -t subscribe "[\"window\"]" || swaymsg reload; } | { \
	if swaymsg "[con_id=__focused__ tiling] focus"; then \
		swaymsg "[workspace=__focused__ floating] kill"; \
		swaymsg focus prev && swaymsg "focus next; floating enable"; \
	elif swaymsg "[con_id=__focused__ floating] focus"; then \
		dbus; \
	else \
		dbus; \
	fi; \
}'

# super/alt+<num>:
# if Application.screens[num] is not empty, just focus the screen, otherwise move the current window along,
# and store its appid and title, in ~/.config/ushell/screens
# super/alt+0 removes the window from the screen and the config file
#
# if appid and title matches a line in $HOME/.config/ushell/screens, create the surface in that screen

# hide cursor after 8 seconds, and when typing begins

bindsym Mod4+BackSpace kill
bindsym Mod1+Escape kill

bindsym --release Super_L dbus
bindsym --release Super_R dbus
bindsym Mod1+Tab dbus

mode lock {
	bindsym --release Super_L dbus
	bindsym --release Super_R dbus
	bindsym Mod1+Tab dbus
}

workspace_auto_back_and_forth yes

exec python3 $$USHELL_DIR/swaylay.py

no_focus [app_id=swaydim]
for_window [app_id=swaydim] opacity 0.5, floating enable, resize grow 100ppt

# https://github.com/jjsullivan5196/wvkbd
# https://git.sr.ht/~earboxer/swipeGuess

# lock
# switch to workspace lock, go to lock mode, and if workspace is empty, run: uni lock
# super, alt+tab or click on statusbar: toggle password prompt
# password prompt closes (showing  in lock mode) when Escape is pressed,
# 	or when empty password is entered, or simply when password prompt is unfocused
# start in locked mode
# lock after 10m idle, if lock inhibit is not active
# before lock, show a 10s countdown screen
#
# check for the password of user "nu":
# su nu -c true
#
# plugged in: lock after 10 min idle, turn off display after 15 min idle
# battery: decrease brightness after 5 min idle, lock after 10 min idle, turn off display after 11 min idle
# low battery: decrease brightness after 2 min idle, lock and turn off display after 4 min idle,
# 	suspend after 5 min idle
# https://wiki.archlinux.org/title/Backlight
# https://github.com/FedeDP/Clight/wiki/Modules#wayland-support
# https://quickshell.org/docs/v0.1.0/types/Quickshell.Widgets/WrapperItem/
# https://doc.qt.io/qt-6/qml-qtquick-effects-multieffect.html
#
# https://wiki.archlinux.org/title/Power_management
# battery
# power profiles (latency config) https://docs.kernel.org/power/pm_qos_interface.html
# 	https://github.com/linrunner/TLP
# https://github.com/Hummer12007/brightnessctl
#
# 30s idle after lock, poweroff screen
# in modern systems, other hardwares (cpu, network ...) are automatically put into low consumption (high latency) mode,
# 	unless an application specifically request for low latency using Linux PM QoS
# 	https://docs.kernel.org/power/pm_qos_interface.html
